version: '3.8'
services:
  web:
    build:
      context: ../..
      dockerfile: deployment/prod/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../..:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - DEBUG=1
    env_file:
      - ../../.env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../..
      dockerfile: deployment/prod/Dockerfile
    command: celery -A config worker -l info --pool=solo
    volumes:
      - ../..:/app
    env_file:
      - ../../.env
    environment:
      - DJANGO_ENV=development
      - DEBUG=1
    depends_on:
      - redis
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ecommerce_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  dev_postgres_data:
  media_volume:
