version: '3.8'
services:
  web:
    build:
      context: ../..
      dockerfile: deployment/prod/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    environment:
      - DJANGO_ENV=prod
    depends_on:
      - redis
      - db
    volumes:
      - static_volume:/app/static  # Persistent static files

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: ../..
      dockerfile: deployment/prod/Dockerfile
    command: celery -A config worker -l info
    env_file:
      - ../../.env
    environment:
      - DJANGO_ENV=prod
    depends_on:
      - redis
      - db
    volumes:
      - static_volume:/app/static

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  prod_postgres_data:
  static_volume: